services:
  app:
    build: .
    image: devops-learning:compose
    container_name: devops-learning-app
    environment:
      APP_ENV: development
    ports:
      - "5000:5000"
    restart: unless-stopped
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops_password
      POSTGRES_DB: devopsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
