name: DevOps Learning Deployment

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        default: "1.0.2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment started
        run: |
          echo "Deploying image tag: ${{ inputs.image_tag }}"
